#!/usr/bin/env bash

copy() {
	local SOURCES="$1Sources"
	echo "Copy $SOURCES"
 	cp -a $SOURCES ../Fluenti 2>/dev/null
}

echo "Fluenti generator by LiveUI"
echo "Update SPM folder (original code)"

#cd ./SPM && rm -f Package.resolved && rm -rf .build && swift package generate-xcodeproj
s
echo "Clean Fluenti folder, all but essentials"
cd ./Fluenti

mkdir -p ../.tmp

cp .gitignore ../.tmp/.gitignore
cp Package.swift ../.tmp/Package.swift
cp LICENSE ../.tmp/LICENSE
cp README.md ../.tmp/README.md

find . ! -name '.git' -type f -exec rm -rf {} +

cp ../.tmp/.gitignore .gitignore
cp ../.tmp/Package.swift Package.swift
cp ../.tmp/LICENSE LICENSE
cp ../.tmp/README.md README.md

rm -rf ../.tmp

echo "Move SPM Project and Fluenti stuff over"
cp -rf ../SPM/Fluenti.xcodeproj ./
cp -rf ../SPM/Sources ./
cp -rf ../SPM/Tests ./

echo "Manage dependencies:"

cd ../SPM/
shopt -s dotglob
shopt -s nullglob
CHECKOUTS=(.build/checkouts/*/)
for CHECKOUT in "${CHECKOUTS[@]}"
	do copy $CHECKOUT
done

echo "Gnerate new project with moved dependencies"
cd ../Fluenti
rm -rf ./Fluenti.xcodeproj
swift package generate-xcodeproj
mv ./Fluenti.xcodeproj/xcshareddata/xcschemes/Fluenti-Package.xcscheme ./Fluenti.xcodeproj/xcshareddata/xcschemes/Fluenti.xcscheme
sed -i -e 's/Fluenti-Package/Fluenti/g' ./Fluenti.xcodeproj/xcshareddata/xcschemes/xcschememanagement.plist


echo "Change project to iOS"
# TODO: Improve handing of the hardcoded values below!!!
sed -i -e 's/\$(TOOLCHAIN_DIR)\/usr\/lib\/swift\/macosx//g' ./Fluenti.xcodeproj/project.pbxproj
sed -i -e 's/SDKROOT = "macosx"/SDKROOT = "iphoneos"/g' ./Fluenti.xcodeproj/project.pbxproj
sed -i -e 's/MACOSX_DEPLOYMENT_TARGET = "10.10"/IPHONEOS_DEPLOYMENT_TARGET = "11.3"/g' ./Fluenti.xcodeproj/project.pbxproj

echo "Commit changes to git"
git add -A
git commit -m "autogenerated update"


